### ISSUE TITLE
Sporadic false positives as of 0.1.7

### ISSUE THREAD

**Issue by IgorMinar** [fent/node-stream-equal#5]
Cross-referencing https://github.com/angular/gulp-clang-format/issues/7 here in case someone else is seeing the same issue with stream-equal v0.1.7.

**Comment by fent** [comment]
Looked through their code and don't see the library using stream-equal anywhere. Did I miss something?

**Comment by fent** [comment]
Update?

**Comment by IgorMinar** [comment]
It's used here:
https://github.com/angular/gulp-clang-format/blob/master/index.js#L8

**Comment by fent** [comment]
It's only in that one line. The module is only require'd, but never called.

**Comment by IgorMinar** [comment]
Ah, you are right.

It looks like the code for recently refactored and stream-equal is no
longer used. See
https://github.com/angular/gulp-clang-format/commit/ed23574fdac308cc4f0bdc5b3c6c5c731ae1cf19

I saw the bug described in this issue while stream-equal was still being
actively used by that gulp plugin.

**Comment by fent** [comment]
Not able to repro :/
